### ISSUE TITLE
Errore prefissi mancanti nell'esportazione

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/eddy#103]
Se si prova con la versione 1.2.0 a esportare l'ontologia [INAIL](https://github.com/obdasystems/inail-almawave/tree/master/ontologia/INAIL) si ha il seguente errore:

```
Traceback (most recent call last):
  File "OWLDataFactoryImpl.java", line 277, in uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.getOWLObjectProperty
  File "DefaultPrefixManager.java", line 203, in org.semanticweb.owlapi.util.DefaultPrefixManager.getIRI
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "eddy/core/exporters/owl2.py", line 1771, in run
  File "eddy/core/exporters/owl2.py", line 582, in convert
  File "eddy/core/exporters/owl2.py", line 1101, in getRole
eddy.core.exporters.owl2.org.semanticweb.owlapi.model.OWLRuntimeException: org.semanticweb.owlapi.model.OWLRuntimeException: Prefix not registered for prefix name: skos:
```

**Comment by valeriosantarelli** [comment]
Confermo, sta restituendo anche a me questo errore.
Lo fa anche con la versione "1.2.1" che ha messo a disposizione Manuel qualche giorno fa a questo link: http://dl.bintray.com/obdasystems/eddy-builds/1.2.0/master/

Con la 1.1.2 invece non ci sono problemi, e nemmeno con la versione 3.0.

Allego il file .graphol:

[INAIL.graphol.zip](https://github.com/obdasystems/eddy/files/4621595/INAIL.graphol.zip)

In ogni caso a questo punto credo non abbia particolare senso usare per INAIL la versione 1.2.
Usiamo la 1.1.2 (tanto in meno ha praticamente solo il ridimensionamento del font), e poi quando è pronta usiamo la 3.

**Comment by mnamici** [comment]
Per la versione 1.2 il problema dovrebbe essere risolto ora, lo includiamo nella 1.2.1.
