### ISSUE TITLE
Errore salvataggio e annotazioni sull'ontologia

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#109]
Segnalazione da Gianluca Pepe, che sta provando la v3 per l'integrazione con Grapholscape:

```
Alcune note sulla compatibilità con la nuova versione di Eddy, ci sono un paio di cose che non sono riuscito a testare:
- Datatype Restrictions: ottengo un errore quando vado ad aggiungere il datatype in input, per i facet invece non ci sono problemi
- Annotazioni sull'ontologia: riesco ad aggiungere le annotazioni ma poi ricevo un errore quando vado a salvare (In realtà però la sintassi mi sembra uguale alle
  annotazioni sulle entità che ho invece testato, quindi credo funzionino)
```

```
Dunque, il problema riguarda il salvataggio, ma non ottengo un errore specifico sulle annotazioni.
In generale quando creo un progetto e lo salvo per la prima volta cliccando sull'icona nella toolbar e scegliendo poi la posizione, ottengo questo errore:

    Traceback (most recent call last):

      File "eddy\ui\session.py", line 2777, in doSave

      File "eddy\core\exporters\graphol_iri.py", line 717, in run

      File "eddy\core\exporters\graphol_iri.py", line 692, in createProjectFile

      File "eddy\core\exporters\graphol_iri.py", line 690, in createProjectFile

      File "eddy\core\functions\fsystem.py", line 124, in fwrite

      File "eddy\core\functions\fsystem.py", line 100, in fremove

    PermissionError: [WinError 32] Impossibile accedere al file. Il file è utilizzato da un altro processo: 'C:\\Users\\Gianluca\\Downloads\\test.graphol'


Andando poi nella cartella che avevo selezionato mi trovo però due file salvati: test.graphol e .test.graphol.
Adesso se apro test.graphol mi trovo un progetto vuoto, se apro .test.graphol invece trovo il progetto con le modifiche fatte.
Facendo modifiche su uno dei due file e poi salvandole, non ricevo nessun errore, le modifiche vengono effettivamente salvate ad eccezione delle annotazioni sull'ontologia.
```

**Comment by NonnonePalmiro** [comment]
Sono riuscito a ricreare l'errore sul server, in settimana analizzo la problematica e cerco di risolvere.

Ricordiamoci di testare (i.e., far testare a Giacomo...) nuove funzionalità di salvataggio anche su ambiente Unix

**Comment by NonnonePalmiro** [comment]
Il problema sembra essere stato corretto (nel senso che ho fatto girare sul server e lì è andato tutto a posto, ma con differenti versioni di windows non si può mai dire...). 
Ho buildato il nuovo eseguibile per windows e l'ho caricato su Drive (Eddy-3.0.0-windows_amd64.exe) così in caso si può passare a Gianluca la versione più recente

**Comment by valeriosantarelli** [comment]
Il problema del salvataggio è stato risulto su macchina Windows, Gianluca ha testato, e sta funzionando.

Rimane il problema del salvataggio delle annotazioni dell'ontologia, ma è un problema separato, per non fare confusione chiudo qui e apro una issue diversa.
