### ISSUE TITLE
Errore avvio 3.1.dev0 64 bit  su windows 10 

### ISSUE THREAD

**Issue by NonnonePalmiro** [obdasystems/eddy#125]
All'avvio di un progetto viene ritornato il seguente errore (che sulle verisoni precedenti non si verifica):

Traceback (most recent call last):
  File "eddy\core\application.py", line 350, in doCreateSession
  File "eddy\core\application.py", line 335, in doCreateSession
  File "eddy\ui\session.py", line 323, in __init__
  File "eddy\core\loaders\owl2.py", line 152, in __init__
  File "eddy\core\jvm\__init__.py", line 569, in initialize
  File "jpype\_core.py", line 222, in startJVM
SystemError: java.lang.ClassNotFoundException: org.jpype.classloader.DynamicClassLoader

**Comment by NonnonePalmiro** [comment]
Succede anche provando ad utilizzare la versione per 32 bit

**Comment by mnamici** [comment]
Succede su tutte le piattaforme dopo il freeze a partire da 756ce34554, tra la versione 1.0 e 1.1 jpype ha aggiunto un jar di classi native che non avevo notato aggiornando i requisiti. Va fatto includere nel freeze (nel classpath ci pensa jpype). Per riferimento il jar si chiama org.jpype.jar. 
A breve committo il fix.

**Comment by mnamici** [comment]
Sembra che il problema sia stato risolto upstream con un hook per pyinstaller (vedi pull 877 su jpype). 
Localmente funziona, ora aspettiamo i build e verifichiamo.

**Comment by NonnonePalmiro** [comment]
Ottimo, grazie manuel
