### ISSUE TITLE
Errore definizione DatatypeDefinition

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#177]
Il tentativo di costruire un `DatatypeDefinition` (quello in figura) risulta nell'errore che riporto sotto:

![Schermata 2022-01-20 alle 11 40 15](https://user-images.githubusercontent.com/8250758/150323360-c6a10233-d0df-474f-b2db-b7e5d98314c0.png)

```
Traceback (most recent call last):
  File "eddy/core/diagram.py", line 417, in mouseMoveEvent
  File "eddy/core/profiles/common.py", line 118, in checkEdge
  File "eddy/core/profiles/rules/owl2.py", line 518, in __call__
  File "eddy/core/owl.py", line 2186, in forDatatype
KeyError: http:///www.obdasystems.com/testontology/teenageInteger
```

L'errore viene generato al momento di attaccare l'input edge dal nodo `Datatype` al nodo operatore `data`.

**Comment by mnamici** [comment]
Per essere sicuri, intendi proprio `DatatypeDefinition` o `DatatypeRestriction`? Perché a meno che non sto capendo male quell'espressione costruisce la seconda delle due.

**Comment by valeriosantarelli** [comment]
Allora io stavo provando a costruire un assioma di questo tipo qui:

```
DatatypeDefinition(:personAge DatatypeRestriction(xsd:integer xsd:minInclusive "0"^^xsd:integer xsd:maxInclusive "150"^^xsd:integer)) 
```

La DatatypeRestriction me l'ha fatta fare, ma poi quando provo a definire la DatatypeDefinition va in errore. Forse sto sbagliando io?

**Comment by mnamici** [comment]
Per come è implementato attualmente, nella figura sopra il nodo `Datatype` che stai collegando in input al nodo operatore `data` in realtà rappresenta il tipo su cui stai applicando la restrizione, ovvero il primo argomento di `DatatypeRestriction`. Quindi collegando l'arco input dal nodo `test:teenageInteger` al nodo `data` avresti come traduzione l'espressione:
```
DatatypeRestriction(
    test:teenageInteger 
    xsd:minInclusive     "13"^^xsd:integer 
    xsd:maxInclusive    "19"^^xsd:integer
)
```
L'eccezione esce fuori quando viene fatta la verifica che le constraining facet connesse al nodo `data` (nel caso sopra `xsd:minInclusive` e `xsd:maxInclusive`) siano ammesse per il `Datatype` specificato (`test:teenageInteger`), e poiché si tratta di un datatype custom queste non sono definite.
Questo chiaramente va risolto però per quanto riguarda la specifica di assiomi `DatatypeDefinition` non credo ci sia proprio il modo di definirli attualmente in Eddy.

**Comment by valeriosantarelli** [comment]
Mi sa che hai ragione in effetti. Si può definire una DatatypeRestriction, un datatype custom, ma una DatatypeDefinition mi sa proprio di no.

**Comment by valeriosantarelli** [comment]
Riprendo questa issue perchè è emersa di nuovo questa esigenza, e onestamente, mi ero del tutto dimenticato che non avessimo attualmente il supporto per costriure un assioma di tipo `DataTypeDefinition`.

Il tipo di assioma che vorremmo modellare è questo (chiaramente questo è un esempio):

```
DatatypeDefinition(
   :toddlerAge
   DataOneOf( "1"^^xsd:integer "2"^^xsd:integer ) 
 ) 
```

Mi pare che ricada nella casistica del punto 2 di [questo](https://github.com/obdasystems/eddy/issues/177#issuecomment-1017719529) commento di Manuel.

**Comment by valeriosantarelli** [comment]
Per una `DataTypeDefinition` che prende in input una `DataTypeRestriction` si potrebbe utilizzare una costruzione grafica che prevede:

1. La definizione di un custom datatype
2. il nodo `data` con in input un datatype e i facet richiesti
3. un arco di equivalenza tra custom datatype e nodo `data`


Ovvero questo (aggiungendo l'arco):

<img width="348" height="329" alt="Image" src="https://github.com/user-attachments/assets/f225faa5-c07e-42e7-9d31-64cf03a826f5" />

Nel caso di un DatatypeDefinition con un DataOneOf (come nell'esempio del commento precedente), si potrebbe usare:

1. La definizione do un custom datatype
2. il nodo `oneOf` con in input dei literals
3. un arco di equivalenza tra custom datatype e nodo `oneOf`

Ovvero questo (aggiungendo l'arco):

<img width="550" height="394" alt="Image" src="https://github.com/user-attachments/assets/61a03019-e2ca-4fd8-949d-224c8c7bb4dd" />

Al momento il nodo oneOf già supporta il contrllo che non si possono dare in input prima una clssse e poi un individuals (o viceversa), ma poi sembra che ci sia un problema in fase di esportazione, perchè ad esempio il caso qui sotto genera un errore in fase di check della sintassi OWL, e anche in fase di esportazione, ovviamente.

<img width="829" height="453" alt="Image" src="https://github.com/user-attachments/assets/85aff670-a970-46f8-933b-4a9a8480cb0b" />
