### ISSUE TITLE
[BUG]: Creazione datatype

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/eddy#273]
### Describe the bug

Mentre definivo un nodo datatype mi è comparso questo errore:

![image](https://github.com/obdasystems/eddy/assets/36189778/8fb6c665-4909-4382-9629-34e379a8cabd)

### Reproduction Steps

Creare nuovo datatype con valore dateTime

### Affected Versions

3.5.1

### Installation

Windows Installer

### Operating System

Windows

### Operating System Version

Windows 10

### Operating System Architecture

x86_64

### Log

```sh
Traceback (most recent call last):
  File "eddy\ui\iri.py", line 687, in accept
  File "eddy\core\items\nodes\common\base.py", line 764, in iri
  File "eddy\core\items\nodes\common\base.py", line 833, in doUpdateNodeLabel
  File "eddy\core\owl.py", line 2027, in iriLabelString
  File "eddy\core\owl.py", line 2040, in renderByPrefixedIRI
  File "eddy\core\owl.py", line 1808, in getShortestPrefixedForm
  File "eddy\core\owl.py", line 1792, in getPrefixedForms
  File "eddy\core\owl.py", line 1776, in getMatchingPrefixes
  File "eddy\core\owl.py", line 502, in __init__
RuntimeError: wrapped C/C++ object of type Project has been deleted
```

**Comment by giacomoronconiobda** [comment]
Riavviando Eddy il problema si risolve e riesco a creare il nodo dataType

**Comment by mnamici** [comment]
Hai per caso importato qualche diagramma? Perché il fatto che l'istanza del progetto risulti deallocata è molto strano, forse rimane il riferimento al progetto temporaneo durante l'importazione.

**Comment by giacomoronconiobda** [comment]
No, non mi pare. Avevo già fatto delle modifiche all'ontologia ma purtroppo non saprei riprodurlo... Speravo si riuscisse a capire dallo stack trace

L'ho ha visto accadere anche @MariaRosariaFraraccio , forse ha notato qualcos'altro
