### ISSUE TITLE
Fatal error!

### ISSUE THREAD

**Issue by ymagallanes** [obdasystems/eddy#35]
When I try to init Eddy show this error:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/travis/build/obdasystems/eddy/scripts/initscripts/ConsoleSetLibPath.py", line 44, in run
  File "run.py", line 174, in <module>
  File "run.py", line 169, in main
  File "/home/travis/build/obdasystems/eddy/eddy/core/application.py", line 140, in configure
TypeError: 'NoneType' object is not iterable

I use ubuntu 18.04.3  LTS x64
Eddy version 1.1.2

Thanks in advance

**Comment by mnamici** [comment]
Thanks for the bug report. 

The issues seems related to the serialization of the list of recent projects, unfortunately though, I'm not able to reproduce it on a fresh install of Ubuntu 18.04.3 using the 1.1.2 release so I don't know exactly what's causing it. 

Can you please try to remove the `recent` key from the `[project]` section in the application settings file and see if that solves the issue? Its a plain text file named `Eddy.conf` and is located under the `~/.config/Sapienza University/` directory.
 
You can remove the line that starts with `recent=`.

**Comment by ymagallanes** [comment]
Hello Mnamici,
This work for my.
Thanks a lot!!
Regards
