### ISSUE TITLE
Importazione diagrammi Graphml

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#39]
Tentando di importare un diagramma Graphml, ottengo il seguente errore:

Traceback (most recent call last):
  File "eddy/ui/session.py", line 1550, in doImport
  File "eddy/core/loaders/graphml.py", line 868, in run
  File "eddy/core/loaders/graphml.py", line 835, in projectMerge
  File "eddy/core/project.py", line 2120, in run
  File "eddy/core/project.py", line 1925, in mergeDiagrams
  File "eddy/ui/dialogs.py", line 58, in __init__
  File "eddy/core/common.py", line 1371, in __init__
  File "eddy/core/common.py", line 431, in __init__
TypeError: 'project' is an unknown keyword argument

Il diagramma è in allegato:

[telecom.graphml.zip](https://github.com/obdasystems/eddy/files/3904462/telecom.graphml.zip)

**Comment by mnamici** [comment]
Il problema di importazione da Graphml è stato risolto in 17b24bb. 

Per quanto riguarda il diagramma allegato ci sono dei costrutti malformati (prevalentemente archi di input invertiti) che ne impediscono la traduzione in OWL, ma questo è un altro problema.
