### ISSUE TITLE
Errore apertura dell'ontology manager

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#62]
Il tentativo di aprire l'ontology manager in un nuovo progetto (definiti solo parametri iniziali e creato un nuovo diagramma), ha generato il seguente errore:

Traceback (most recent call last):
  File "eddy/ui/session.py", line 2994, in doOpenOntologyExplorer
  File "eddy/ui/ontology.py", line 416, in __init__
  File "eddy/ui/ontology.py", line 500, in redraw
  File "eddy/core/project.py", line 214, in ontologyIRIString
TypeError: 'NoneType' object is not iterable

**Comment by valeriosantarelli** [comment]
Chiudo, l'ontology manager si apre correttamente.
