### ISSUE TITLE
Errore su cancellazione nodo

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#72]
La cancellazione di un qualsiasi tipo di nodo dal diagramma produce il seguente errore:

Traceback (most recent call last):
  File "eddy/core/project.py", line 1347, in doRemoveItem
  File "eddy/core/project.py", line 1841, in removeIRIOccurenceFromDiagram
  File "eddy/core/project.py", line 1866, in removeTypedIRIOccurenceFromDiagram
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by NonnonePalmiro** [comment]
Il problema dovrebbe essere risolto da versione beta 2.0.0 del 13/03/2020

**Comment by valeriosantarelli** [comment]
Confermo. Chiudo la issue.
